export const  FETCH_DATA_COME = 'FETCH_DATA_COME'
export const  FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_ERROR = 'FETCH_DATA_ERROR';
export const FETCH_DATA_DELETE = 'FETCH_DATA_DELETE';
export const FETCH_DATA_EDIT = 'FETCH_DATA_EDIT';